CREATE TABLE movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    genre VARCHAR(100),
    release_year INT,
    director VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO movies (title, genre, release_year, director) VALUES
    ('Um Sonho de Liberdade', 'Drama', 1994, 'Frank Darabont'),
    ('O Poderoso Chefão', 'Crime', 1972, 'Francis Ford Coppola'),
    ('Batman: O Cavaleiro das Trevas', 'Ação', 2008, 'Christopher Nolan'),
    ('Pulp Fiction: Tempo de Violência', 'Crime', 1994, 'Quentin Tarantino'),
    ('Forrest Gump: O Contador de Histórias', 'Drama', 1994, 'Robert Zemeckis'),
    ('A Origem', 'Ficção Científica', 2010, 'Christopher Nolan'),
    ('Clube da Luta', 'Drama', 1999, 'David Fincher'),
    ('Matrix', 'Ficção Científica', 1999, 'Lana Wachowski, Lilly Wachowski'),
    ('O Senhor dos Anéis: O Retorno do Rei', 'Fantasia', 2003, 'Peter Jackson'),
    ('O Poderoso Chefão: Parte II', 'Crime', 1974, 'Francis Ford Coppola'),
    ('Star Wars: O Império Contra-Ataca', 'Ficção Científica', 1980, 'Irvin Kershner'),
    ('Interestelar', 'Ficção Científica', 2014, 'Christopher Nolan'),
    ('Cidade de Deus', 'Crime', 2002, 'Fernando Meirelles, Kátia Lund'),
    ('O Resgate do Soldado Ryan', 'Guerra', 1998, 'Steven Spielberg'),
    ('Os Infiltrados', 'Crime', 2006, 'Martin Scorsese'),
    ('Gladiador', 'Ação', 2000, 'Ridley Scott'),
    ('O Lobo de Wall Street', 'Biografia', 2013, 'Martin Scorsese'),
    ('Vingadores: Ultimato', 'Ação', 2019, 'Anthony Russo, Joe Russo'),
    ('O Silêncio dos Inocentes', 'Thriller', 1991, 'Jonathan Demme'),
    ('A Lista de Schindler', 'História', 1993, 'Steven Spielberg'),
    ('V de Vingança', 'Ação', 2005, 'James McTeigue'),
    ('Bastardos Inglórios', 'Guerra', 2009, 'Quentin Tarantino'),
    ('O Pianista', 'Biografia', 2002, 'Roman Polanski'),
    ('Um Estranho no Ninho', 'Drama', 1975, 'Milos Forman'),
    ('Parasita', 'Thriller', 2019, 'Bong Joon Ho'),
    ('Django Livre', 'Western', 2012, 'Quentin Tarantino'),
    ('Jogos, Trapaças e Dois Canos Fumegantes', 'Crime', 1998, 'Guy Ritchie'),
    ('A Vida é Bela', 'Comédia', 1997, 'Roberto Benigni'),
    ('Brilho Eterno de uma Mente Sem Lembranças', 'Drama', 2004, 'Michel Gondry'),
    ('Os Suspeitos', 'Drama', 1995, 'Bryan Singer'),
    ('O Grande Lebowski', 'Comédia', 1998, 'Joel Coen, Ethan Coen'),
    ('O Sexto Sentido', 'Thriller', 1999, 'M. Night Shyamalan'),
    ('O Profissional', 'Ação', 1994, 'Luc Besson'),
    ('Scarface', 'Crime', 1983, 'Brian De Palma'),
    ('Laranja Mecânica', 'Ficção Científica', 1971, 'Stanley Kubrick'),
    ('Beleza Americana', 'Drama', 1999, 'Sam Mendes'),
    ('O Show de Truman', 'Drama', 1998, 'Peter Weir'),
    ('O Exterminador do Futuro 2: O Julgamento Final', 'Ação', 1991, 'James Cameron'),
    ('Senhor dos Anéis: A Sociedade do Anel', 'Fantasia', 2001, 'Peter Jackson'),
    ('Os Sete Samurais', 'Ação', 1954, 'Akira Kurosawa'),
    ('Cidadão Kane', 'Drama', 1941, 'Orson Welles'),
    ('Blade Runner: O Caçador de Andróides', 'Ficção Científica', 1982, 'Ridley Scott'),
    ('Psicose', 'Terror', 1960, 'Alfred Hitchcock'),
    ('O Iluminado', 'Terror', 1980, 'Stanley Kubrick'),
    ('Taxi Driver', 'Drama', 1976, 'Martin Scorsese'),
    ('O Grande Truque', 'Mistério', 2006, 'Christopher Nolan'),
    ('O Fabuloso Destino de Amélie Poulain', 'Comédia', 2001, 'Jean-Pierre Jeunet'),
    ('Clube dos Cinco', 'Drama', 1985, 'John Hughes'),
    ('Ratatouille', 'Animação', 2007, 'Brad Bird, Jan Pinkava'),
    ('De Volta para o Futuro', 'Ficção Científica', 1985, 'Robert Zemeckis'),
    ('O Rei Leão', 'Animação', 1994, 'Roger Allers, Rob Minkoff'),
    ('O Labirinto do Fauno', 'Fantasia', 2006, 'Guillermo del Toro'),
    ('Toy Story', 'Animação', 1995, 'John Lasseter'),
    ('A Princesa Prometida', 'Fantasia', 1987, 'Rob Reiner'),
    ('O Incrível Hulk', 'Ação', 2008, 'Louis Leterrier'),
    ('Os Caça-Fantasmas', 'Comédia', 1984, 'Ivan Reitman'),
    ('Indiana Jones e a Última Cruzada', 'Ação', 1989, 'Steven Spielberg'),
    ('Jurassic Park: Parque dos Dinossauros', 'Aventura', 1993, 'Steven Spielberg'),
    ('O Estranho Mundo de Jack', 'Animação', 1993, 'Henry Selick'),
    ('Titanic', 'Romance', 1997, 'James Cameron'),
    ('Jurassic World', 'Aventura', 2015, 'Colin Trevorrow'),
    ('O Diabo Veste Prada', 'Comédia', 2006, 'David Frankel'),
    ('Homem-Aranha: De Volta ao Lar', 'Ação', 2017, 'Jon Watts'),
    ('Pantera Negra', 'Ação', 2018, 'Ryan Coogler'),
    ('Frozen: Uma Aventura Congelante', 'Animação', 2013, 'Chris Buck, Jennifer Lee'),
    ('Moana: Um Mar de Aventuras', 'Animação', 2016, 'Ron Clements, John Musker'),
    ('Os Vingadores', 'Ação', 2012, 'Joss Whedon'),
    ('Mulher-Maravilha', 'Ação', 2017, 'Patty Jenkins'),
    ('Capitão América: O Soldado Invernal', 'Ação', 2014, 'Anthony Russo, Joe Russo'),
    ('Harry Potter e a Pedra Filosofal', 'Fantasia', 2001, 'Chris Columbus'),
    ('Guardiões da Galáxia', 'Ação', 2014, 'James Gunn'),
    ('Deadpool', 'Ação', 2016, 'Tim Miller'),
    ('Star Wars: O Despertar da Força', 'Ficção Científica', 2015, 'J.J. Abrams'),
    ('Homem de Ferro', 'Ação', 2008, 'Jon Favreau'),
    ('Doutor Estranho', 'Ação', 2016, 'Scott Derrickson'),
    ('Thor: Ragnarok', 'Ação', 2017, 'Taika Waititi'),
    ('Aquaman', 'Ação', 2018, 'James Wan'),
    ('Liga da Justiça', 'Ação', 2017, 'Zack Snyder'),
    ('Homem-Aranha: Longe de Casa', 'Ação', 2019, 'Jon Watts'),
    ('O Espetacular Homem-Aranha', 'Ação', 2012, 'Marc Webb'),
    ('Batman Begins', 'Ação', 2005, 'Christopher Nolan'),
    ('Shazam!', 'Ação', 2019, 'David F. Sandberg'),
    ('Venom', 'Ação', 2018, 'Ruben Fleischer'),
    ('O Incrível Hulk', 'Ação', 2008, 'Louis Leterrier'),
    ('X-Men: Dias de um Futuro Esquecido', 'Ação', 2014, 'Bryan Singer'),
    ('X-Men: Primeira Classe', 'Ação', 2011, 'Matthew Vaughn'),
    ('Homem-Formiga', 'Ação', 2015, 'Peyton Reed'),
    ('Capitão Marvel', 'Ação', 2019, 'Anna Boden, Ryan Fleck'),
    ('O Homem de Aço', 'Ação', 2013, 'Zack Snyder'),
    ('Thor', 'Ação', 2011, 'Kenneth Branagh'),
    ('Batman vs Superman: A Origem da Justiça', 'Ação', 2016, 'Zack Snyder'),
    ('Homem de Ferro 2', 'Ação', 2010, 'Jon Favreau'),
    ('Homem de Ferro 3', 'Ação', 2013, 'Shane Black'),
    ('Vingadores: Era de Ultron', 'Ação', 2015, 'Joss Whedon'),
    ('Homem-Formiga e a Vespa', 'Ação', 2018, 'Peyton Reed'),
    ('Capitão América: Guerra Civil', 'Ação', 2016, 'Anthony Russo, Joe Russo'),
    ('Os Vingadores: Guerra Infinita', 'Ação', 2018, 'Anthony Russo, Joe Russo'),
    ('Homem-Aranha no Aranhaverso', 'Animação', 2018, 'Peter Ramsey, Rodney Rothman, Bob Persichetti');